import { once } from "node:events";
import type { AddressInfo } from "node:net";
import { afterEach, describe, expect, it } from "vitest";
import { MemoryIdentityRepository } from "../src/auth/repository.js";
import { IdentityService } from "../src/auth/service.js";
import { createApp } from "../src/app.js";
import { createHarness, searchTool } from "./fixtures/harness.js";

describe("console authentication and API",()=>{
  const cleanup:Array<()=>Promise<void>>=[]; afterEach(async()=>{for(const item of cleanup.splice(0).reverse())await item();});
  async function start(){const h=createHarness();const identity=new IdentityService(new MemoryIdentityRepository());const app=createApp({projects:h.projects,reviews:h.reviews,health:h.health,credentials:h.credentials,catalog:h.catalog,gateway:h.gateway},"admin-key-with-at-least-24-chars","127.0.0.1",undefined,{identity,repository:h.repository,projects:h.projects,reviews:h.reviews,health:h.health,credentials:h.credentials});const server=app.listen(0,"127.0.0.1");await once(server,"listening");cleanup.push(()=>new Promise<void>((resolve,reject)=>server.close(e=>e?reject(e):resolve())));return{h,identity,base:`http://127.0.0.1:${(server.address() as AddressInfo).port}`};}
  const post=(body:unknown)=>({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});
  it("registers, logs in, uses an HttpOnly session and logs out",async()=>{const {base}=await start();const registered=await fetch(`${base}/api/auth/register`,post({username:"member.one",displayName:"成员一",password:"strong-password-123"}));expect(registered.status).toBe(201);expect((await registered.json()).data.user.role).toBe("member");const login=await fetch(`${base}/api/auth/login`,post({username:"member.one",password:"strong-password-123"}));expect(login.status).toBe(200);const cookie=login.headers.get("set-cookie")!;expect(cookie).toContain("HttpOnly");expect(cookie).toContain("SameSite=Lax");const session=await fetch(`${base}/api/auth/session`,{headers:{cookie}});expect(session.status).toBe(200);const logout=await fetch(`${base}/api/auth/logout`,{...post({}),headers:{...post({}).headers,cookie}});expect(logout.status).toBe(204);expect((await fetch(`${base}/api/auth/session`,{headers:{cookie}})).status).toBe(401);});
  it("registers and lists an MCP project without exposing the project token",async()=>{const {base,h}=await start();h.connector.add("http://console.test/mcp",[searchTool()],"secret-project-token");await fetch(`${base}/api/auth/register`,post({username:"owner.one",displayName:"负责人",password:"strong-password-123"}));const login=await fetch(`${base}/api/auth/login`,post({username:"owner.one",password:"strong-password-123"}));const cookie=login.headers.get("set-cookie")!;const created=await fetch(`${base}/api/projects`,{...post({projectKey:"console",displayName:"控制台项目",description:"控制台真实接入",endpoint:"http://console.test/mcp",projectToken:"secret-project-token"}),headers:{...post({}).headers,cookie}});expect(created.status).toBe(201);const text=await created.text();expect(text).not.toContain("secret-project-token");expect(text).not.toContain("credentialCiphertext");const listed=await fetch(`${base}/api/projects`,{headers:{cookie}});expect(listed.status).toBe(200);expect((await listed.json()).data).toHaveLength(1);});
  it("keeps an approved version diff relative to its previous approved version",async()=>{const {base,h,identity}=await start();const owner=await identity.register("diff.owner","差异负责人","strong-password-123");h.connector.add("http://diff.test/v1",[searchTool("初始说明")]);const first=await h.projects.register({projectKey:"diff",displayName:"差异项目",description:"验证历史版本差异",endpoint:"http://diff.test/v1",projectToken:"project-token",ownerId:owner.id});await h.reviews.submit(first.version.id,owner.id);await h.reviews.decide(first.version.id,"approved","reviewer-1","首版通过");h.connector.add("http://diff.test/v2",[searchTool("更新说明")]);const second=await h.projects.createVersion({projectKey:"diff",endpoint:"http://diff.test/v2",projectToken:"project-token",submittedBy:owner.id});await h.reviews.submit(second.version.id,owner.id);await h.reviews.decide(second.version.id,"approved","reviewer-1","升级通过");const login=await fetch(`${base}/api/auth/login`,post({username:"diff.owner",password:"strong-password-123"}));const cookie=login.headers.get("set-cookie")!;const firstDetail=await (await fetch(`${base}/api/versions/${first.version.id}`,{headers:{cookie}})).json();expect(firstDetail.data.diffBaseVersionNo).toBeNull();expect(firstDetail.data.diff).toEqual([expect.objectContaining({name:"search",change:"added"})]);const secondDetail=await (await fetch(`${base}/api/versions/${second.version.id}`,{headers:{cookie}})).json();expect(secondDetail.data.diffBaseVersionNo).toBe(1);expect(secondDetail.data.diff).toEqual([expect.objectContaining({name:"search",change:"description_changed"})]);});
  it("prevents ordinary members from listing users",async()=>{const {base}=await start();await fetch(`${base}/api/auth/register`,post({username:"member.two",displayName:"成员二",password:"strong-password-123"}));const login=await fetch(`${base}/api/auth/login`,post({username:"member.two",password:"strong-password-123"}));const response=await fetch(`${base}/api/users`,{headers:{cookie:login.headers.get("set-cookie")!}});expect(response.status).toBe(403);});
});
