CREATE TABLE mcp_projects (
  id CHAR(36) NOT NULL COMMENT '项目主键 UUID',
  project_key VARCHAR(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL COMMENT '稳定项目标识及工具名前缀',
  display_name VARCHAR(120) NOT NULL COMMENT '项目展示名称',
  description VARCHAR(1000) NOT NULL COMMENT '项目能力说明',
  owner_id VARCHAR(64) NOT NULL COMMENT '项目负责人平台身份',
  status VARCHAR(16) NOT NULL DEFAULT 'pending' COMMENT 'pending/active/disabled/retired',
  trusted_review_bypass_enabled BOOLEAN NOT NULL DEFAULT FALSE COMMENT '可信项目免审开关，默认关闭',
  active_version_id CHAR(36) NULL COMMENT '当前生效服务版本',
  health_status VARCHAR(16) NOT NULL DEFAULT 'unknown' COMMENT 'unknown/healthy/unhealthy',
  last_health_checked_at DATETIME(6) NULL COMMENT 'UTC 最近探活完成时间',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'UTC 创建时间',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'UTC 更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_mcp_projects_project_key (project_key),
  KEY idx_mcp_projects_status_health (status, health_status),
  CONSTRAINT ck_mcp_projects_status CHECK (status IN ('pending', 'active', 'disabled', 'retired')),
  CONSTRAINT ck_mcp_projects_health CHECK (health_status IN ('unknown', 'healthy', 'unhealthy'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MCP 接入项目';

CREATE TABLE mcp_service_versions (
  id CHAR(36) NOT NULL COMMENT '服务版本主键 UUID',
  project_id CHAR(36) NOT NULL COMMENT '所属项目',
  version_no BIGINT UNSIGNED NOT NULL COMMENT '项目内递增版本号',
  endpoint VARCHAR(2048) NOT NULL COMMENT '标准 MCP 服务地址',
  protocol_version VARCHAR(32) NOT NULL COMMENT 'MCP 协议版本',
  credential_ciphertext TEXT NULL COMMENT '项目调用凭据密文',
  credential_key_id VARCHAR(64) NULL COMMENT '加密密钥版本标识',
  review_status VARCHAR(24) NOT NULL DEFAULT 'draft' COMMENT 'draft/pending_review/approved/rejected',
  risk_level VARCHAR(16) NOT NULL DEFAULT 'low' COMMENT 'low/medium/high/incompatible',
  definition_hash BINARY(32) NOT NULL COMMENT '连接与工具定义 SHA-256',
  submitted_by VARCHAR(64) NOT NULL COMMENT '提交者平台身份',
  submitted_at DATETIME(6) NULL COMMENT 'UTC 提交审核或免审批准时间，草稿为空',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'UTC 创建时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_mcp_service_versions_id_project (id, project_id),
  UNIQUE KEY uk_mcp_service_versions_project_version (project_id, version_no),
  KEY idx_mcp_service_versions_project_hash (project_id, definition_hash),
  KEY idx_mcp_service_versions_review_submitted (review_status, submitted_at),
  CONSTRAINT ck_mcp_service_versions_review CHECK (review_status IN ('draft', 'pending_review', 'approved', 'rejected')),
  CONSTRAINT ck_mcp_service_versions_risk CHECK (risk_level IN ('low', 'medium', 'high', 'incompatible')),
  CONSTRAINT fk_mcp_service_versions_project FOREIGN KEY (project_id) REFERENCES mcp_projects (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MCP 服务不可变版本';

ALTER TABLE mcp_projects
  ADD CONSTRAINT fk_mcp_projects_active_version FOREIGN KEY (active_version_id, id) REFERENCES mcp_service_versions (id, project_id) ON UPDATE RESTRICT ON DELETE RESTRICT;

CREATE TABLE mcp_tool_versions (
  id CHAR(36) NOT NULL COMMENT '工具版本主键 UUID',
  service_version_id CHAR(36) NOT NULL COMMENT '所属服务版本',
  original_name VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL COMMENT '服务原始工具名',
  description TEXT NOT NULL COMMENT '工具说明',
  input_schema JSON NOT NULL COMMENT '原始输入定义',
  output_schema JSON NULL COMMENT '原始输出定义',
  risk_level VARCHAR(16) NOT NULL DEFAULT 'low' COMMENT 'low/medium/high/incompatible',
  PRIMARY KEY (id),
  UNIQUE KEY uk_mcp_tool_versions_service_name (service_version_id, original_name),
  CONSTRAINT ck_mcp_tool_versions_risk CHECK (risk_level IN ('low', 'medium', 'high', 'incompatible')),
  CONSTRAINT fk_mcp_tool_versions_service FOREIGN KEY (service_version_id) REFERENCES mcp_service_versions (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='每个服务版本的 MCP 工具定义';

CREATE TABLE mcp_tool_runtime (
  project_id CHAR(36) NOT NULL COMMENT '所属项目',
  original_name VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL COMMENT '项目内稳定工具名称',
  status VARCHAR(16) NOT NULL DEFAULT 'active' COMMENT 'active/suspended',
  suspended_reason VARCHAR(1000) NULL COMMENT '暂停原因，正常状态为空',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'UTC 更新时间',
  PRIMARY KEY (project_id, original_name),
  CONSTRAINT ck_mcp_tool_runtime_status CHECK (status IN ('active', 'suspended')),
  CONSTRAINT ck_mcp_tool_runtime_reason CHECK (status <> 'suspended' OR (suspended_reason IS NOT NULL AND CHAR_LENGTH(TRIM(suspended_reason)) > 0)),
  CONSTRAINT fk_mcp_tool_runtime_project FOREIGN KEY (project_id) REFERENCES mcp_projects (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MCP 工具当前运行状态';

CREATE TABLE mcp_reviews (
  service_version_id CHAR(36) NOT NULL COMMENT '被审核服务版本',
  decision VARCHAR(16) NOT NULL COMMENT 'approved/rejected/bypassed',
  comment VARCHAR(2000) NULL COMMENT '审核意见，驳回时必填',
  reviewer_id VARCHAR(64) NOT NULL COMMENT '审核人平台身份',
  decided_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'UTC 决策时间',
  PRIMARY KEY (service_version_id),
  KEY idx_mcp_reviews_reviewer_time (reviewer_id, decided_at),
  CONSTRAINT ck_mcp_reviews_decision CHECK (decision IN ('approved', 'rejected', 'bypassed')),
  CONSTRAINT ck_mcp_reviews_rejected_comment CHECK (decision <> 'rejected' OR (comment IS NOT NULL AND CHAR_LENGTH(TRIM(comment)) > 0)),
  CONSTRAINT fk_mcp_reviews_service FOREIGN KEY (service_version_id) REFERENCES mcp_service_versions (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='MCP 服务版本审核记录';

CREATE TABLE mcp_call_credentials (
  id CHAR(36) NOT NULL COMMENT '调用凭据主键 UUID',
  owner_id VARCHAR(64) NOT NULL COMMENT '凭据所属平台用户',
  credential_name VARCHAR(120) NOT NULL COMMENT '用户可识别的凭据名称',
  token_prefix VARCHAR(16) NOT NULL COMMENT '令牌展示与定位前缀',
  token_digest BINARY(32) NOT NULL COMMENT '令牌 SHA-256 摘要',
  expires_at DATETIME(6) NULL COMMENT 'UTC 过期时间',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'UTC 创建时间',
  revoked_at DATETIME(6) NULL COMMENT 'UTC 吊销时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_mcp_call_credentials_digest (token_digest),
  KEY idx_mcp_call_credentials_owner_created (owner_id, created_at),
  CONSTRAINT ck_mcp_call_credentials_expiry CHECK (expires_at IS NULL OR expires_at > created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='统一网关调用凭据';

CREATE TABLE platform_users (
  id CHAR(36) NOT NULL COMMENT '平台账号 UUID',
  username VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL COMMENT '全局唯一且不可修改的登录用户名',
  display_name VARCHAR(120) NOT NULL COMMENT '账号展示名称',
  password_hash VARCHAR(255) NOT NULL COMMENT 'Argon2id 密码摘要',
  role VARCHAR(16) NOT NULL DEFAULT 'member' COMMENT 'member/reviewer/operator',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'UTC 创建时间',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'UTC 更新时间',
  CONSTRAINT pk_platform_users PRIMARY KEY (id),
  CONSTRAINT uk_platform_users_username UNIQUE (username),
  KEY idx_platform_users_role_created (role, created_at, id),
  CONSTRAINT ck_platform_users_role CHECK (role IN ('member', 'reviewer', 'operator'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='LinkCli 控制台账号';

CREATE TABLE platform_sessions (
  id CHAR(36) NOT NULL COMMENT '登录会话 UUID',
  user_id CHAR(36) NOT NULL COMMENT '所属平台账号',
  token_digest BINARY(32) NOT NULL COMMENT '会话令牌 SHA-256 摘要',
  expires_at DATETIME(6) NOT NULL COMMENT 'UTC 滑动过期时间',
  last_seen_at DATETIME(6) NOT NULL COMMENT 'UTC 最近有效访问时间',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'UTC 创建时间',
  revoked_at DATETIME(6) NULL COMMENT 'UTC 主动注销时间',
  CONSTRAINT pk_platform_sessions PRIMARY KEY (id),
  CONSTRAINT uk_platform_sessions_token_digest UNIQUE (token_digest),
  KEY idx_platform_sessions_user_created (user_id, created_at, id),
  KEY idx_platform_sessions_expiry (expires_at),
  CONSTRAINT ck_platform_sessions_expiry CHECK (expires_at > created_at),
  CONSTRAINT fk_platform_sessions_user FOREIGN KEY (user_id) REFERENCES platform_users (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='LinkCli 控制台登录会话';

CREATE TABLE mcp_call_outbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '调用接收顺序及物理主键',
  event_id CHAR(36) NOT NULL COMMENT '单次工具调用 UUID',
  schema_version SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '事件契约版本',
  credential_id CHAR(36) NOT NULL COMMENT '调用凭据',
  platform_owner_id VARCHAR(64) NOT NULL COMMENT '调用凭据所属平台用户快照',
  client_conversation_id VARCHAR(128) NULL COMMENT '宿主生成的聊天标识',
  client_turn_id VARCHAR(128) NULL COMMENT '宿主生成的一轮对话标识',
  client_turn_sequence BIGINT UNSIGNED NULL COMMENT '宿主提供的聊天内轮次序号',
  transport_session_id VARCHAR(128) NULL COMMENT '可选传输会话提示，不作为轮次真值',
  session_source VARCHAR(16) NOT NULL DEFAULT 'missing' COMMENT 'mcp/custom/missing',
  attribution_hint VARCHAR(24) NOT NULL COMMENT 'client_turn/session_question/credential_question/missing',
  user_question TEXT NULL COMMENT '用户原始问题明文，缺失归属时可空',
  question_fingerprint BINARY(32) NULL COMMENT '规范化问题 HMAC-SHA-256',
  normalization_version SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '问题规范化算法版本',
  project_id CHAR(36) NOT NULL COMMENT '被调用项目',
  service_version_id CHAR(36) NOT NULL COMMENT '实际调用服务版本',
  tool_version_id CHAR(36) NOT NULL COMMENT '实际调用工具版本',
  project_key VARCHAR(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL COMMENT '项目标识快照',
  tool_name VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL COMMENT '原始工具名快照',
  arguments_summary JSON NOT NULL COMMENT '脱敏截断后的调用参数摘要',
  result_summary JSON NULL COMMENT '脱敏截断后的调用结果摘要',
  call_status VARCHAR(16) NOT NULL DEFAULT 'started' COMMENT 'started/completed/partial',
  outcome VARCHAR(16) NOT NULL DEFAULT 'unknown' COMMENT 'success/error/unknown',
  call_error_code VARCHAR(64) NULL COMMENT '稳定业务调用错误分类，不保存敏感正文',
  validation_signals JSON NOT NULL COMMENT '问题质量与归属观测信号',
  started_at DATETIME(6) NOT NULL COMMENT 'UTC 调用开始时间',
  completed_at DATETIME(6) NULL COMMENT 'UTC 调用结束时间',
  duration_ms BIGINT UNSIGNED NULL COMMENT '调用耗时毫秒',
  delivery_status VARCHAR(16) NOT NULL DEFAULT 'waiting' COMMENT 'waiting/ready/processing/delivered/dead_letter',
  delivery_attempts INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '采集投递次数',
  next_attempt_at DATETIME(6) NULL COMMENT 'UTC 下次投递时间',
  lease_owner VARCHAR(128) NULL COMMENT '当前 Worker 租约标识',
  lease_until DATETIME(6) NULL COMMENT 'UTC 租约截止时间',
  delivered_at DATETIME(6) NULL COMMENT 'UTC 成功投递时间',
  last_error_code VARCHAR(64) NULL COMMENT '最后一次投递错误分类，不保存敏感正文',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'UTC 创建时间',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'UTC 更新时间',
  CONSTRAINT pk_mcp_call_outbox PRIMARY KEY (id),
  CONSTRAINT uk_mcp_call_outbox_event UNIQUE (event_id),
  KEY idx_mcp_call_outbox_delivery (delivery_status, next_attempt_at, id),
  KEY idx_mcp_call_outbox_retention (delivery_status, updated_at, id),
  KEY idx_mcp_call_outbox_started (call_status, started_at, id),
  KEY idx_mcp_call_outbox_credential_time (credential_id, started_at, id),
  CONSTRAINT ck_mcp_call_outbox_session_source CHECK (session_source IN ('mcp','custom','missing')),
  CONSTRAINT ck_mcp_call_outbox_attribution CHECK (attribution_hint IN ('client_turn','session_question','credential_question','missing')),
  CONSTRAINT ck_mcp_call_outbox_call_status CHECK (call_status IN ('started','completed','partial')),
  CONSTRAINT ck_mcp_call_outbox_outcome CHECK (outcome IN ('success','error','unknown')),
  CONSTRAINT ck_mcp_call_outbox_delivery CHECK (delivery_status IN ('waiting','ready','processing','delivered','dead_letter')),
  CONSTRAINT fk_mcp_call_outbox_credential FOREIGN KEY (credential_id) REFERENCES mcp_call_credentials (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mcp_call_outbox_project FOREIGN KEY (project_id) REFERENCES mcp_projects (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mcp_call_outbox_service_version FOREIGN KEY (service_version_id) REFERENCES mcp_service_versions (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mcp_call_outbox_tool_version FOREIGN KEY (tool_version_id) REFERENCES mcp_tool_versions (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='L1 可靠调用事件与投递队列';

CREATE TABLE mcp_turns (
  id CHAR(36) NOT NULL COMMENT '轮次实例 UUID',
  credential_id CHAR(36) NOT NULL COMMENT '调用凭据',
  platform_owner_id VARCHAR(64) NOT NULL COMMENT '调用方平台用户快照',
  client_conversation_id VARCHAR(128) NULL COMMENT '宿主聊天标识',
  client_turn_id VARCHAR(128) NULL COMMENT '宿主轮次标识',
  client_turn_sequence BIGINT UNSIGNED NULL COMMENT '宿主提供的聊天内轮次序号',
  exact_turn_key BINARY(32) NULL COMMENT '精确模式唯一 HMAC 键',
  transport_session_id VARCHAR(128) NULL COMMENT '兼容模式连接范围',
  candidate_key BINARY(32) NOT NULL COMMENT '精确或兼容归组候选 HMAC 键',
  attribution_method VARCHAR(24) NOT NULL COMMENT 'client_turn/session_question/credential_question/unavailable',
  user_question TEXT NULL COMMENT '代表性用户原始问题，九十天后清空',
  question_fingerprint BINARY(32) NULL COMMENT '规范化问题 HMAC-SHA-256',
  normalization_version SMALLINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '规范化算法版本',
  lifecycle_status VARCHAR(16) NOT NULL DEFAULT 'collecting' COMMENT 'collecting/grace/finalized',
  settlement_status VARCHAR(16) NOT NULL DEFAULT 'pending' COMMENT 'pending/succeeded/failed',
  quality_status VARCHAR(16) NOT NULL COMMENT 'trusted/inferred/suspicious/missing/partial',
  end_reason VARCHAR(24) NULL COMMENT 'idle_timeout/call_limit/client_end/administrative',
  first_event_at DATETIME(6) NOT NULL COMMENT 'UTC 首次调用开始时间',
  last_event_at DATETIME(6) NOT NULL COMMENT 'UTC 最后一次调用开始时间',
  grace_until DATETIME(6) NULL COMMENT 'UTC 迟到等待截止时间',
  finalized_at DATETIME(6) NULL COMMENT 'UTC 首次定稿时间',
  late_revision_until DATETIME(6) NULL COMMENT 'UTC 允许迟到修订截止时间',
  call_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '调用数',
  error_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '错误调用数',
  execution_outcome VARCHAR(32) NOT NULL DEFAULT 'unknown' COMMENT 'all_calls_succeeded/recovered_after_error/ended_with_error/unknown',
  canonical_chain JSON NULL COMMENT '不含参数值的规范调用链',
  chain_signature BINARY(32) NULL COMMENT '规范调用链 SHA-256',
  signature_version SMALLINT UNSIGNED NULL COMMENT '签名算法版本',
  behavior_signals JSON NOT NULL COMMENT '可观测行为信号',
  settlement_revision INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '结算版本',
  settlement_attempts INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前结算版本失败次数',
  next_settlement_at DATETIME(6) NULL COMMENT 'UTC 下次允许结算时间',
  last_settlement_error VARCHAR(64) NULL COMMENT '最后结算错误分类',
  details_purged_at DATETIME(6) NULL COMMENT 'UTC 正文与明细清理时间',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'UTC 创建时间',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'UTC 更新时间',
  CONSTRAINT pk_mcp_turns PRIMARY KEY (id),
  CONSTRAINT uk_mcp_turns_exact_key UNIQUE (exact_turn_key),
  KEY idx_mcp_turns_open_candidate (candidate_key, lifecycle_status, last_event_at, id),
  KEY idx_mcp_turns_owner_time (platform_owner_id, first_event_at, id),
  KEY idx_mcp_turns_quality_time (quality_status, first_event_at, id),
  KEY idx_mcp_turns_finalize (lifecycle_status, grace_until, id),
  KEY idx_mcp_turns_idle (lifecycle_status, updated_at, id),
  KEY idx_mcp_turns_settlement (lifecycle_status, settlement_status, next_settlement_at, finalized_at, id),
  CONSTRAINT ck_mcp_turns_attribution CHECK (attribution_method IN ('client_turn','session_question','credential_question','unavailable')),
  CONSTRAINT ck_mcp_turns_lifecycle CHECK (lifecycle_status IN ('collecting','grace','finalized')),
  CONSTRAINT ck_mcp_turns_settlement CHECK (settlement_status IN ('pending','succeeded','failed')),
  CONSTRAINT ck_mcp_turns_quality CHECK (quality_status IN ('trusted','inferred','suspicious','missing','partial')),
  CONSTRAINT ck_mcp_turns_end_reason CHECK (end_reason IS NULL OR end_reason IN ('idle_timeout','call_limit','client_end','administrative')),
  CONSTRAINT ck_mcp_turns_execution CHECK (execution_outcome IN ('all_calls_succeeded','recovered_after_error','ended_with_error','unknown')),
  CONSTRAINT fk_mcp_turns_credential FOREIGN KEY (credential_id) REFERENCES mcp_call_credentials (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='对话轮次与长期结算摘要';

CREATE TABLE mcp_call_events (
  event_id CHAR(36) NOT NULL COMMENT '单次工具调用 UUID',
  turn_id CHAR(36) NULL COMMENT '所属轮次；无法归属时为空',
  ingress_order BIGINT UNSIGNED NOT NULL COMMENT 'L1 持久接收顺序',
  credential_id CHAR(36) NOT NULL COMMENT '调用凭据',
  project_id CHAR(36) NOT NULL COMMENT '被调用项目',
  service_version_id CHAR(36) NOT NULL COMMENT '实际调用服务版本',
  tool_version_id CHAR(36) NOT NULL COMMENT '实际调用工具版本',
  project_key VARCHAR(48) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL COMMENT '项目标识快照',
  tool_name VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_bin NOT NULL COMMENT '工具名快照',
  user_question TEXT NULL COMMENT '本次调用携带的问题原文',
  arguments_summary JSON NOT NULL COMMENT '脱敏参数摘要',
  result_summary JSON NULL COMMENT '脱敏结果摘要',
  call_status VARCHAR(16) NOT NULL COMMENT 'completed/partial',
  outcome VARCHAR(16) NOT NULL COMMENT 'success/error/unknown',
  call_error_code VARCHAR(64) NULL COMMENT '稳定业务调用错误分类，不保存敏感正文',
  validation_signals JSON NOT NULL COMMENT '质量观测信号',
  started_at DATETIME(6) NOT NULL COMMENT 'UTC 调用开始时间',
  completed_at DATETIME(6) NULL COMMENT 'UTC 调用结束时间',
  duration_ms BIGINT UNSIGNED NULL COMMENT '调用耗时毫秒',
  received_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'UTC L2 接收时间',
  CONSTRAINT pk_mcp_call_events PRIMARY KEY (event_id),
  KEY idx_mcp_call_events_turn_order (turn_id, started_at, ingress_order, event_id),
  KEY idx_mcp_call_events_project_time (project_id, started_at, event_id),
  KEY idx_mcp_call_events_tool_time (tool_version_id, started_at, event_id),
  KEY idx_mcp_call_events_credential_time (credential_id, started_at, event_id),
  KEY idx_mcp_call_events_retention (started_at, event_id),
  CONSTRAINT ck_mcp_call_events_status CHECK (call_status IN ('completed','partial')),
  CONSTRAINT ck_mcp_call_events_outcome CHECK (outcome IN ('success','error','unknown')),
  CONSTRAINT fk_mcp_call_events_turn FOREIGN KEY (turn_id) REFERENCES mcp_turns (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mcp_call_events_credential FOREIGN KEY (credential_id) REFERENCES mcp_call_credentials (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mcp_call_events_project FOREIGN KEY (project_id) REFERENCES mcp_projects (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mcp_call_events_service_version FOREIGN KEY (service_version_id) REFERENCES mcp_service_versions (id) ON UPDATE RESTRICT ON DELETE RESTRICT,
  CONSTRAINT fk_mcp_call_events_tool_version FOREIGN KEY (tool_version_id) REFERENCES mcp_tool_versions (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='九十天单次 MCP 调用明细';

CREATE TABLE mcp_analysis_outbox (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '投递顺序主键',
  event_id CHAR(36) NOT NULL COMMENT '分析事件 UUID',
  turn_id CHAR(36) NOT NULL COMMENT '所属轮次',
  settlement_revision INT UNSIGNED NOT NULL COMMENT '轮次结算版本',
  event_type VARCHAR(16) NOT NULL COMMENT 'upsert/retract',
  payload JSON NOT NULL COMMENT '不含密钥的轮次结算载荷',
  delivery_status VARCHAR(16) NOT NULL DEFAULT 'pending' COMMENT 'pending/processing/delivered/dead_letter',
  delivery_attempts INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '投递次数',
  next_attempt_at DATETIME(6) NULL COMMENT 'UTC 下次投递时间',
  lease_owner VARCHAR(128) NULL COMMENT '当前 Worker 租约标识',
  lease_until DATETIME(6) NULL COMMENT 'UTC 租约截止时间',
  delivered_at DATETIME(6) NULL COMMENT 'UTC 成功投递时间',
  last_error_code VARCHAR(64) NULL COMMENT '最后错误分类',
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'UTC 创建时间',
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'UTC 更新时间',
  CONSTRAINT pk_mcp_analysis_outbox PRIMARY KEY (id),
  CONSTRAINT uk_mcp_analysis_outbox_event UNIQUE (event_id),
  CONSTRAINT uk_mcp_analysis_outbox_revision UNIQUE (turn_id, settlement_revision, event_type),
  KEY idx_mcp_analysis_outbox_delivery (delivery_status, next_attempt_at, id),
  CONSTRAINT ck_mcp_analysis_outbox_type CHECK (event_type IN ('upsert','retract')),
  CONSTRAINT ck_mcp_analysis_outbox_delivery CHECK (delivery_status IN ('pending','processing','delivered','dead_letter')),
  CONSTRAINT fk_mcp_analysis_outbox_turn FOREIGN KEY (turn_id) REFERENCES mcp_turns (id) ON UPDATE RESTRICT ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='L2 向分析层可靠投递队列';
