import { Router, type NextFunction, type Request, type Response } from "express";
import { z } from "zod";
import { clearSessionCookie, parseCookies, requireConsoleRole, requireSameOrigin, requireSession, SESSION_COOKIE, setSessionCookie } from "../auth/middleware.js";
import type { IdentityService } from "../auth/service.js";
import type { RegistryRepository } from "../db/repository.js";
import type { PlatformUser, Project } from "../domain.js";
import { AppError, assertFound } from "../errors.js";
import type { CredentialService } from "../gateway/auth.js";
import type { HealthMonitor } from "../registry/health-monitor.js";
import type { ProjectService } from "../registry/project-service.js";
import type { ReviewService } from "../registry/review-service.js";
import { credentialView, diffTools, projectView, reviewView, toolView, userView, versionView } from "./views.js";
import { paginate } from "./pagination.js";
import type { StatisticsService } from "../statistics/service.js";
import { createStatisticsRouter } from "../statistics/http.js";
import type { AnalysisRepository } from "../analysis/repository.js";
import type { SkillService } from "../skill/service.js";

const authSchema=z.object({username:z.string(),password:z.string()});
const registerSchema=authSchema.extend({displayName:z.string()});
const projectSchema=z.object({projectKey:z.string(),displayName:z.string(),description:z.string(),endpoint:z.string().url(),projectToken:z.string().min(1).max(4096).optional()});
const versionSchema=z.object({endpoint:z.string().url(),projectToken:z.string().min(1).max(4096).optional()});
const roleSchema=z.object({role:z.enum(["member","reviewer","operator"])});
const reviewSchema=z.object({decision:z.enum(["approved","rejected"]),comment:z.string().max(2000).optional()});
const statusSchema=z.object({action:z.enum(["disable","enable","retire"])});
const bypassSchema=z.object({enabled:z.boolean()});
const credentialSchema=z.object({credentialName:z.string().min(1).max(120),expiresAt:z.string().datetime().nullable().optional()});
const skillValidationSchema=z.object({trigger:z.enum(["generation","revision","dependency_change","runtime_anomaly","manual"])});
const skillReviewSchema=z.object({decision:z.enum(["approved","rejected"]),comment:z.string().max(1000).nullable().optional()});
const skillLifecycleSchema=z.object({action:z.enum(["activate","pause","resume","degrade","retire"]),reason:z.string().max(255).nullable().optional()});
const page=(req:Request)=>({cursor:typeof req.query.cursor==="string"?req.query.cursor:undefined,limit:Math.min(100,Math.max(1,Number(req.query.limit)||20))});
const canView=(user:PlatformUser,project:Project)=>user.id===project.ownerId||user.role==="reviewer"||user.role==="operator";
const assertView=(user:PlatformUser,project:Project)=>{if(!canView(user,project))throw new AppError("AUTHORIZATION_FAILED","Project is not available to this account",403);};

export interface ConsoleServices { identity:IdentityService; repository:RegistryRepository; projects:ProjectService; reviews:ReviewService; health:HealthMonitor; credentials:CredentialService; statistics?:StatisticsService; analysis?:AnalysisRepository; skills?:SkillService; }

class AttemptLimiter {
  private readonly entries=new Map<string,{count:number;resetAt:number}>();
  check(key:string):void { const now=Date.now();const current=this.entries.get(key);if(!current||current.resetAt<=now){this.entries.set(key,{count:1,resetAt:now+10*60_000});return;}if(current.count>=10)throw new AppError("RATE_LIMITED","Too many attempts; try again later",429);current.count+=1; }
  clear(key:string):void { this.entries.delete(key); }
}

export function createConsoleRouter(services:ConsoleServices, secureCookie:boolean):Router {
  const router=Router(); const attempts=new AttemptLimiter(); router.use(requireSameOrigin);
  router.post("/auth/register",async(req,res,next)=>{try{const b=registerSchema.parse(req.body);attempts.check(`register:${req.ip}`);res.status(201).json({data:{user:userView(await services.identity.register(b.username,b.displayName,b.password))}});}catch(e){next(e);}});
  router.post("/auth/login",async(req,res,next)=>{const b=authSchema.parse(req.body);const key=`login:${req.ip}:${b.username.trim()}`;try{attempts.check(key);const result=await services.identity.login(b.username,b.password);attempts.clear(key);setSessionCookie(res,result.token,result.session.expiresAt,secureCookie);res.json({data:{user:userView(result.user),session:{expiresAt:result.session.expiresAt}}});}catch(e){next(e);}});
  router.post("/auth/logout",async(req,res,next)=>{try{const token=parseCookies(req.header("cookie"))[SESSION_COOKIE];if(token)await services.identity.logout(token);clearSessionCookie(res,secureCookie);res.status(204).end();}catch(e){next(e);}});
  router.use(requireSession(services.identity,secureCookie));
  if (services.statistics) router.use("/statistics", createStatisticsRouter(services.statistics));
  router.get("/auth/session",(req,res)=>res.json({data:{user:userView(req.consoleUser!),session:{expiresAt:req.consoleSession!.expiresAt}}}));
  router.patch("/me",async(req,res,next)=>{try{const b=z.object({displayName:z.string()}).parse(req.body);res.json({data:{user:userView(await services.identity.updateDisplayName(req.consoleUser!.id,b.displayName))}});}catch(e){next(e);}});

  const visibleClusters=async(user:PlatformUser)=>{if(!services.analysis)return[];const projects=await services.repository.listProjects();const visibleIds=new Set(projects.filter(project=>user.role!=="member"||project.ownerId===user.id).map(project=>project.id));return(await services.analysis.listClusters()).filter(cluster=>user.role!=="member"||(cluster.projectScope!==null&&cluster.projectScope.split("→").every(id=>visibleIds.has(id))));};
  if(services.analysis){
    router.get("/analysis/clusters",async(req,res,next)=>{try{const rows=(await visibleClusters(req.consoleUser!)).sort((a,b)=>b.lastSeenAt.getTime()-a.lastSeenAt.getTime());res.json({data:rows.map(({centroidVector:_vector,...cluster})=>cluster)});}catch(e){next(e);}});
    router.get("/analysis/clusters/:id",async(req,res,next)=>{try{const id=Number(req.params.id);const cluster=(await visibleClusters(req.consoleUser!)).find(item=>item.id===id);if(!cluster)throw new AppError("NOT_FOUND","Query cluster not found",404);const [scenes,candidate]=await Promise.all([services.analysis!.listScenes(id),services.analysis!.findLatestCandidate(id)]);const{centroidVector:_vector,...view}=cluster;res.json({data:{cluster:view,scenes,candidate}});}catch(e){next(e);}});
  }
  if(services.skills){
    const visibleSkills=async(user:PlatformUser)=>{const rows=await services.skills!.list();if(user.role!=="member")return rows;const clusterIds=new Set((await visibleClusters(user)).map(cluster=>cluster.id));return rows.filter(skill=>clusterIds.has(skill.sourceClusterId));};
    router.get("/skills",async(req,res,next)=>{try{res.json({data:await visibleSkills(req.consoleUser!)});}catch(e){next(e);}});
    router.get("/skills/:id",async(req,res,next)=>{try{const id=String(req.params.id);if(!(await visibleSkills(req.consoleUser!)).some(skill=>skill.id===id))throw new AppError("NOT_FOUND","Skill not found",404);res.json({data:await services.skills!.detail(id)});}catch(e){next(e);}});
    router.post("/skills/:id/validate",requireConsoleRole(["operator"]),async(req,res,next)=>{try{const body=skillValidationSchema.parse(req.body);res.status(202).json({data:{job:await services.skills!.enqueueValidation(String(req.params.id),body.trigger)}});}catch(e){next(e);}});
    router.post("/skills/:id/review",requireConsoleRole(["reviewer"]),async(req,res,next)=>{try{const body=skillReviewSchema.parse(req.body);res.json({data:await services.skills!.decideReview(String(req.params.id),body.decision,req.consoleUser!.id,body.comment??null)});}catch(e){next(e);}});
    router.post("/skills/:id/lifecycle",requireConsoleRole(["operator"]),async(req,res,next)=>{try{const body=skillLifecycleSchema.parse(req.body);res.json({data:{skill:await services.skills!.lifecycle(String(req.params.id),body.action,body.reason??null)}});}catch(e){next(e);}});
  }

  router.get("/dashboard",async(req,res,next)=>{try{const user=req.consoleUser!;let projects=(await services.repository.listProjects()).filter(p=>user.role==="operator"||p.ownerId===user.id);const versions=(await Promise.all(projects.map(p=>services.repository.listVersions(p.id)))).flat();const credentials=await services.credentials.list(user.id);const pending=user.role==="reviewer"?(await Promise.all((await services.repository.listProjects()).map(p=>services.repository.listVersions(p.id)))).flat().filter(v=>v.reviewStatus==="pending_review"&&v.submittedBy!==user.id):[];const now=Date.now();res.json({data:{projects:{total:projects.length,active:projects.filter(p=>p.status==="active").length,unhealthy:projects.filter(p=>p.healthStatus==="unhealthy").length,pending:projects.filter(p=>p.status==="pending").length},reviews:user.role==="reviewer"?{pending:pending.length,stale:pending.filter(v=>v.submittedAt&&now-v.submittedAt.getTime()>7*86400000).length}:null,credentials:{active:credentials.filter(c=>!c.revokedAt&&(!c.expiresAt||c.expiresAt.getTime()>now)).length,expiringWithinSevenDays:credentials.filter(c=>!c.revokedAt&&c.expiresAt&&c.expiresAt.getTime()>now&&c.expiresAt.getTime()<now+7*86400000).length},attention:[...projects.filter(p=>p.healthStatus==="unhealthy").map(p=>({type:"unhealthy_project",id:p.id,title:p.displayName,description:"项目最近探活不健康",href:`/projects/${p.projectKey}`,occurredAt:(p.lastHealthCheckedAt??p.updatedAt).toISOString()})),...pending.slice(0,5).map(v=>({type:"pending_review",id:v.id,title:`待审核版本 v${v.versionNo}`,description:"候选版本等待审核",href:`/versions/${v.id}`,occurredAt:(v.submittedAt??v.createdAt).toISOString()}))].slice(0,8)}});}catch(e){next(e);}});

  router.get("/projects",async(req,res,next)=>{try{const user=req.consoleUser!;let projects=(await services.repository.listProjects()).filter(p=>user.role!=="member"||p.ownerId===user.id);const q=String(req.query.query??"").toLowerCase();if(q)projects=projects.filter(p=>`${p.projectKey} ${p.displayName}`.toLowerCase().includes(q));if(req.query.status)projects=projects.filter(p=>p.status===req.query.status);if(req.query.healthStatus)projects=projects.filter(p=>p.healthStatus===req.query.healthStatus);const views=await Promise.all(projects.sort((a,b)=>b.updatedAt.getTime()-a.updatedAt.getTime()).map(async p=>{const versions=await services.repository.listVersions(p.id);const latest=versions.at(-1);const tools=latest?await services.repository.listTools(latest.id):[];return projectView(p,versions,tools);}));const result=paginate(views,page(req).cursor,page(req).limit,v=>v.id);res.json({data:result.data,meta:{nextCursor:result.nextCursor}});}catch(e){next(e);}});
  router.post("/projects",async(req,res,next)=>{try{const b=projectSchema.parse(req.body);const result=await services.projects.register({...b,ownerId:req.consoleUser!.id});res.status(201).json({data:{project:projectView(result.project,[result.version],result.tools),version:versionView(result.version),tools:result.tools.map(t=>toolView(result.project.projectKey,t)),allowedActions:["submit_version","create_version","disable_project"]}});}catch(e){next(e);}});

  async function detail(projectKey:string,user:PlatformUser){const project=assertFound(await services.repository.getProjectByKey(projectKey),"Project not found");assertView(user,project);const versions=await services.repository.listVersions(project.id);const latest=versions.at(-1)!;const tools=latest?await services.repository.listTools(latest.id):[];const runtimes=await services.repository.listToolRuntime(project.id);const allowed:string[]=[];if(project.ownerId===user.id&&project.status!=="retired")allowed.push("create_version");if(project.ownerId===user.id&&latest?.reviewStatus==="draft")allowed.push("submit_version");if((project.ownerId===user.id||user.role==="operator")&&project.status!=="retired")allowed.push(project.status==="disabled"?"enable_project":"disable_project");if(user.role==="operator"&&project.status==="disabled")allowed.push("retire_project");if(user.role==="operator")allowed.push("set_trusted_review_bypass");return{project,versions,latest,tools,runtimes,view:{...projectView(project,versions,tools),activeVersion:versions.find(v=>v.id===project.activeVersionId)?versionView(versions.find(v=>v.id===project.activeVersionId)!):null,latestVersion:versionView(latest),tools:tools.map(t=>toolView(project.projectKey,t,runtimes.find(r=>r.originalName===t.originalName))),versions:versions.slice().reverse().map(versionView),allowedActions:allowed}};}
  router.get("/projects/:key",async(req,res,next)=>{try{const result=await detail(String(req.params.key),req.consoleUser!);res.json({data:result.view});}catch(e){next(e);}});
  router.get("/projects/:key/versions",async(req,res,next)=>{try{const d=await detail(String(req.params.key),req.consoleUser!);const result=paginate(d.versions.slice().reverse().map(versionView),page(req).cursor,page(req).limit,v=>v.id);res.json({data:result.data,meta:{nextCursor:result.nextCursor}});}catch(e){next(e);}});
  router.post("/projects/:key/versions",async(req,res,next)=>{try{const b=versionSchema.parse(req.body);const result=await services.projects.createVersion({projectKey:String(req.params.key),...b,submittedBy:req.consoleUser!.id});const project=assertFound(await services.repository.getProjectByKey(String(req.params.key)),"Project not found");res.status(201).json({data:{version:versionView(result.version),tools:result.tools.map(t=>toolView(project.projectKey,t)),suspendedTools:result.suspendedTools}});}catch(e){next(e);}});
  router.patch("/projects/:key/status",async(req,res,next)=>{try{const b=statusSchema.parse(req.body);res.json({data:{project:await services.health.changeProjectStatus(String(req.params.key),b.action,req.consoleUser!.id,req.consoleUser!.role==="operator")}});}catch(e){next(e);}});
  router.patch("/projects/:key/trusted-review-bypass",requireConsoleRole(["operator"]),async(req,res,next)=>{try{const b=bypassSchema.parse(req.body);res.json({data:{project:await services.projects.setTrustedBypass(String(req.params.key),b.enabled)}});}catch(e){next(e);}});

  router.get("/versions/:id",async(req,res,next)=>{try{const version=assertFound(await services.repository.getVersion(String(req.params.id)),"Version not found");const project=assertFound(await services.repository.getProjectById(version.projectId),"Project not found");assertView(req.consoleUser!,project);const versions=await services.repository.listVersions(project.id);const tools=await services.repository.listTools(version.id);const baseVersion=versions.filter(v=>v.versionNo<version.versionNo&&v.reviewStatus==="approved").sort((a,b)=>b.versionNo-a.versionNo)[0];const base=baseVersion?await services.repository.listTools(baseVersion.id):[];const allowed:string[]=[];if(project.ownerId===req.consoleUser!.id&&version.reviewStatus==="draft")allowed.push("submit_version");if(req.consoleUser!.role==="reviewer"&&version.submittedBy!==req.consoleUser!.id&&version.reviewStatus==="pending_review")allowed.push("review_version");res.json({data:{...versionView(version),project:projectView(project,versions,tools),tools:tools.map(t=>toolView(project.projectKey,t)),diffBaseVersionNo:baseVersion?.versionNo??null,diff:diffTools(project.projectKey,base,tools),review:reviewView(await services.repository.getReview(version.id)),allowedActions:allowed}});}catch(e){next(e);}});
  router.post("/versions/:id/submit",async(req,res,next)=>{try{const version=await services.reviews.submit(String(req.params.id),req.consoleUser!.id);const project=assertFound(await services.repository.getProjectById(version.projectId),"Project not found");res.json({data:{version:versionView(version),project,published:project.activeVersionId===version.id}});}catch(e){next(e);}});
  router.get("/reviews",requireConsoleRole(["reviewer"]),async(req,res,next)=>{try{const projects=await services.repository.listProjects();const rows=[];for(const p of projects)for(const v of await services.repository.listVersions(p.id))if(v.reviewStatus==="pending_review"&&v.submittedBy!==req.consoleUser!.id)rows.push({...versionView(v),project:projectView(p,await services.repository.listVersions(p.id),await services.repository.listTools(v.id))});rows.sort((a,b)=>new Date(a.submittedAt??a.createdAt).getTime()-new Date(b.submittedAt??b.createdAt).getTime());const result=paginate(rows,page(req).cursor,page(req).limit,v=>v.id);res.json({data:result.data,meta:{nextCursor:result.nextCursor}});}catch(e){next(e);}});
  router.post("/versions/:id/review",requireConsoleRole(["reviewer"]),async(req,res,next)=>{try{const b=reviewSchema.parse(req.body);const result=await services.reviews.decide(String(req.params.id),b.decision,req.consoleUser!.id,b.comment);res.json({data:{version:versionView(result.version),project:result.project,review:reviewView(await services.repository.getReview(result.version.id)),published:result.published}});}catch(e){next(e);}});

  router.get("/credentials",async(req,res,next)=>{try{const rows=(await services.credentials.list(req.consoleUser!.id)).map(credentialView);const result=paginate(rows,page(req).cursor,page(req).limit,v=>v.id);res.json({data:result.data,meta:{nextCursor:result.nextCursor}});}catch(e){next(e);}});
  router.post("/credentials",async(req,res,next)=>{try{const b=credentialSchema.parse(req.body);const result=await services.credentials.issue(req.consoleUser!.id,b.credentialName,b.expiresAt?new Date(b.expiresAt):null);res.status(201).json({data:{credential:credentialView(result.credential),token:result.token}});}catch(e){next(e);}});
  router.delete("/credentials/:id",async(req,res,next)=>{try{res.json({data:{credential:credentialView(await services.credentials.revoke(String(req.params.id),req.consoleUser!.id))}});}catch(e){next(e);}});
  router.get("/users",requireConsoleRole(["operator"]),async(req,res,next)=>{try{let rows=(await services.identity.listUsers()).map(userView);const q=String(req.query.query??"").toLowerCase();if(q)rows=rows.filter(u=>`${u.username} ${u.displayName}`.toLowerCase().includes(q));if(req.query.role)rows=rows.filter(u=>u.role===req.query.role);const result=paginate(rows,page(req).cursor,page(req).limit,v=>v.id);res.json({data:result.data,meta:{nextCursor:result.nextCursor}});}catch(e){next(e);}});
  router.patch("/users/:id/role",requireConsoleRole(["operator"]),async(req,res,next)=>{try{const b=roleSchema.parse(req.body);res.json({data:{user:userView(await services.identity.changeRole(req.consoleUser!.id,String(req.params.id),b.role))}});}catch(e){next(e);}});
  return router;
}
