import { useQuery } from "@tanstack/react-query";
import { ArrowUpRight, CirclesThreePlus, Path } from "@phosphor-icons/react";
import { Link, useParams } from "react-router-dom";
import { api } from "../../api/client";
import type { ClusterDetail, QueryCluster } from "../../api/types";
import { Empty, LoadError, PageHeader, Status } from "../../components/AppShell";

const percent=(value:number)=>`${(value*100).toFixed(1)}%`;
export function AnalysisPage(){const query=useQuery({queryKey:["analysis","clusters"],queryFn:()=>api<QueryCluster[]>("/api/analysis/clusters")});return <><PageHeader eyebrow="L3 · Query 聚类分析" title="需求聚类" description="按 Project 与有序 Module 路径限定边界，再基于语义证据汇总稳定需求、覆盖缺口和 L4 候选。"/>{query.isError?<LoadError error={query.error} onRetry={()=>query.refetch()}/>:query.isPending?<p className="text-sm text-[#6e6e73]">正在加载 Query 类别…</p>:query.data.length?<div className="grid gap-4 lg:grid-cols-2">{query.data.map(cluster=><Link className="panel panel-interactive group p-6" key={cluster.id} to={`/analysis/clusters/${cluster.id}`}><div className="flex items-start justify-between gap-4"><span className="grid h-11 w-11 place-items-center rounded-[12px] bg-[#eeeef0]"><CirclesThreePlus size={21}/></span><div className="flex gap-2"><Status value={cluster.clusterType}/><Status value={cluster.status}/></div></div><h2 className="mt-7 line-clamp-2 text-xl font-semibold tracking-[-.025em]">{cluster.representativeQuery}</h2><div className="mt-5 flex flex-wrap gap-2 text-xs text-[#6e6e73]"><Path size={15}/><span>{cluster.modulePath?.join(" → ")??"未覆盖模块路径"}</span></div><div className="mt-7 grid grid-cols-3 gap-4 border-t border-[#e3e3e6] pt-5"><Stat label="样本" value={cluster.sampleCount}/><Stat label="独立用户" value={cluster.distinctActorCount}/><Stat label="成功率" value={percent(cluster.sampleCount?cluster.successCount/cluster.sampleCount:0)}/></div><ArrowUpRight className="mt-5 ml-auto transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></Link>)}</div>:<Empty title="还没有 Query 类别" description="L3 消费已结算的可信轮次后，会在这里形成可追溯类别。"/>}</>}

export function ClusterDetailPage(){const{id}=useParams();const query=useQuery({queryKey:["analysis","cluster",id],queryFn:()=>api<ClusterDetail>(`/api/analysis/clusters/${id}`)});const data=query.data;if(query.isError)return <LoadError error={query.error} onRetry={()=>query.refetch()}/>;if(!data)return <p className="text-sm text-[#6e6e73]">正在加载聚类证据…</p>;const c=data.cluster;return <><PageHeader eyebrow={`L3 · 类别 #${c.id}`} title={c.representativeQuery} description={c.modulePath?.join(" → ")??"未识别到完整 Module 路径"}/><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card label="样本 / 用户" value={`${c.sampleCount} / ${c.distinctActorCount}`}/><Card label="执行成功率" value={percent(c.sampleCount?c.successCount/c.sampleCount:0)}/><Card label="输入完整率" value={percent(c.inputCompleteness)}/><Card label="覆盖缺口" value={c.coverageGapCount}/></section><section className="mt-7 grid gap-5 lg:grid-cols-[1fr_360px]"><div className="panel overflow-x-auto"><header className="border-b border-[#e3e3e6] p-5"><h2 className="font-semibold">组内场景</h2><p className="mt-1 text-xs text-[#6e6e73]">具体 Tool 与操作是类别内场景，不改变聚类硬边界</p></header>{data.scenes.length?<table className="data-table"><thead><tr><th>场景</th><th>样本</th><th>成功</th><th>风险</th></tr></thead><tbody>{data.scenes.map((scene,index)=><tr key={`${scene.sceneType}-${index}`}><td><p className="text-sm font-medium">{scene.sceneType}</p><p className="mt-1 text-xs text-[#6e6e73]">{scene.toolPath.map(step=>`${step.moduleId??"?"}.${step.toolName}`).join(" → ")}</p></td><td>{scene.sampleCount}</td><td>{scene.successCount}</td><td><Status value={scene.riskLevel}/></td></tr>)}</tbody></table>:<Empty title="暂无场景" description="更多有效成员进入后会形成操作场景。"/>}</div><aside className="panel h-fit p-6"><p className="eyebrow">L3 → L4</p><h2 className="mt-3 text-xl font-semibold">候选交接</h2>{data.candidate?<><div className="mt-5"><Status value={data.candidate.candidateType}/></div><p className="mt-4 text-sm leading-6 text-[#6e6e73]">类别 v{data.candidate.clusterVersion} 已通过 Outbox 形成幂等候选事件。</p><Link to="/skills" className="btn-secondary mt-5 w-full">查看 Skill 闭环</Link></>:<><p className="mt-4 text-sm leading-6 text-[#6e6e73]">当前仍在观察，或真实 Embedding/Judge 与候选门槛尚未允许交接。</p><Status value={c.status}/></>}</aside></section></>}
function Stat({label,value}:{label:string;value:string|number}){return <div><p className="text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-[#6e6e73]">{label}</p></div>}
function Card({label,value}:{label:string;value:string|number}){return <article className="panel p-5"><p className="eyebrow">{label}</p><p className="mt-5 text-3xl font-semibold tracking-[-.04em]">{value}</p></article>}
